# Generated by Django 5.2.11 on 2026-04-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_number', models.IntegerField(help_text='Unique number for the parking space', unique=True)),
                ('vehicle_type', models.CharField(blank=True, help_text='Type of vehicle (e.g., car, truck, motorcycle)', max_length=50, null=True)),
                ('plate_number', models.CharField(blank=True, help_text='Vehicle license plate number', max_length=20, null=True)),
                ('occupancy_status', models.BooleanField(default=False, help_text='True if occupied, False if free')),
            ],
        ),
    ]
