# Generated by Django 5.2.11 on 2026-04-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='entry_time',
            field=models.DateTimeField(blank=True, help_text='Time when vehicle entered', null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='exit_time',
            field=models.DateTimeField(blank=True, help_text='Time when vehicle exited', null=True),
        ),
    ]
