# Generated by Django 5.2.11 on 2026-04-06 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingspace_entry_time_parkingspace_exit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Vehicle license plate number (exactly 6 characters, letters and digits only, e.g., 603ZPC)', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Plate number must be exactly 6 characters, containing only letters and digits (e.g., 603ZPC).', regex='^[A-Za-z0-9]{6}$')]),
        ),
    ]
