# Generated by Django 5.2.11 on 2026-05-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parkingspace_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Name of the vehicle owner', max_length=100, null=True),
        ),
    ]
